FROM nginx:latest
LABEL org.opencontainers.image.source=https://github.com/describo/collections
LABEL org.opencontainers.image.description="The Describo Collections UI container"
LABEL org.opencontainers.image.licenses=GPLv3

RUN rm /etc/nginx/conf.d/default.conf

COPY ./ui/dist/ /srv/ui/

CMD ["nginx", "-g", "daemon off;"]