FROM tusproject/tusd
LABEL org.opencontainers.image.source=https://github.com/CoEDL/nyingarn-workspace
LABEL org.opencontainers.image.description="The Nyingarn Workspace TUSD container"
LABEL org.opencontainers.image.licenses=GPLv3

USER root
RUN apk update && apk add aws-cli jq bash curl
RUN mkdir -p /root/.aws
COPY tus/config ~/.aws/config
COPY tus/post-finish /srv/tusd-hooks/post-finish
COPY tus/pre-create /srv/tusd-hooks/pre-create
RUN chmod +x /srv/tusd-hooks/*
