name: Build packages and publish to Github Container Registry

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [debian-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the application
        run: ./build-production-containers.sh